### PR TITLE
More state management. Async Return Values. Selectable Barcode types and much more.

### LINKED ISSUE #93: [feature] Add possibility to ignore barcode/qrcode only
Good morning,
at the moment this package provide the possibility to scan barcode o qr code with no limitations. 
I think that a very good improvement can be the possibility to choose if we need to scan barcodes or qrcodes indipendently. Something like:
```dart
QRView(
              onlyQr: true,
              //onlyBarCode: true,
              key: _qrKey,
              onQRViewCreated: _onQRViewCreated,
            ),
```
In my opinion this can be a very good feature that can improve a lot the work that every developer need to make in order to distinguish them.

Thank you

### LINKED ISSUE #103: Option to disable the 'Scanning Unavailable' dialog in iOS
We are building a multilingual application and would like a way to disable the 'Scanning Unavailable' dialog from the plugin, so that we can implement it on our end.

### LINKED ISSUE #107: Restrict Scanned barcode types
Is it/will it be possible to restrict barcode types to specific ones e.g.
  List<BarcodeFormat> selectedFormats = [BarcodeFormat.dataMatrix];

I cannot find a source that indicates how to do this, but it is possible for many barcode scanners.

### LINKED ISSUE #126: Make QRViewController methods return Future<>
Screenshot from 2020-08-17 11-25-25

By default from lib, the resume, pause, flipCamera and dispose methods return void. It would be interesting to return a Future <dynamic> as internal invocations do.

### PR DESCRIPTION
**Pull request by LeLunZ**
With this fork you have more functionality (which was available but not exposed to flutter user):

- State management. Check if your flash is on. controller.flashActive. Check if the users phone has a Backcamera: controller.systemfeatures.hasBackCamera and much more ;)
- Every native call now returns a async function which returns Success or an Error value (Check Class ReturnStatus).
- its possible to turn off/on some functionality. you can turn off/on to show the Native Error dialog when no permission is given. (Native error dialog is also available in android) Or you can disable the flash on controller.dispose
- its possible to call your NativeErrorDialog when you need it (controller.showNativeAlertDialog())
- Its possible to set allowed Barcode types. (controller.setAllowedBarcodeTypes) Only these one will get returned to flutter code. <--- saw that a pull request for that one is appreciated
- a callback to flutter when the permission is handled in the native part. In the callback you can see which permission was given and now you can do more things :)

fixes #126
fixes #107
fixes #103
fixes #93

I forgot to mention that this should not break the current API.

### CODE REVIEW

**Comment by LeLunZ** [comment]
This pull request also simplifies the checking of Permissions on android.

**Comment by bharathiselvan** [comment]
When this will be available in master branch?.., When will the new package be released with these features?..

**Comment by LeLunZ** [comment]
> When this will be available in master branch?.., When will the new package be released with these features?..

Don't know. I still don't know if the repository maintainer will merge this, because the code is a lot more to maintain.
And he isn't that active. 

So currently we are adding the package to our package.yaml like this:

```
qr_code_scanner:
    git:
      url: git://github.com/triply-at/qr_code_scanner.git
      ref: master
```

I will write a email to the maintainer. Lets see what happens ;)

**Comment by bharathiselvan** [comment]
Okay.. Thank you.. :-)

**Comment by LeLunZ** [comment]
With the newest commit you can asks for permissions from everywhere.
Just call QRView.requestCameraPermission()
Thats important, because sometimes you want to asks for permission not on the camera screen.

**Comment by craigbrown-nist** [comment]
Thanks for working on this! 
quick Q: is this the right syntax for restricting types? I can't build it but no errors.
`controller.setAllowedBarcodeTypes([BarcodeFormat.dataMatrix]);
`

**Comment by LeLunZ** [comment]
> Thanks for working on this!
> quick Q: is this the right syntax for restricting types? I can't build it but no syntax errors.
> `controller.setAllowedBarcodeTypes([BarcodeFormat.dataMatrix]);`

What error happens then? 
what does flutter doctor -v say?

So you added this to your yaml?
```
qr_code_scanner:
    git:
      url: git://github.com/triply-at/qr_code_scanner.git
      ref: master
```

Tried a 
`flutter pub update`
`flutter pub get`

Or are you using a outdated flutter version? 
`flutter upgrade`

I think minimum IOS Version needs to be IOS 12.4 or so. (Will check later)

**Comment by craigbrown-nist** [comment]
Upgraded flutter from 1.22.0 to 1.22.1.
Flutter clean and pub get done. 
Confirmed YAML is pulling your git.
IOS 13.3 used.
outpout from flutter doctor -v:
`[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.1 at /Users/craigy/Dev/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/craigy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • ANDROID_HOME = /Users/craigy/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/craigy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] VS Code (version 1.49.2)
    • VS Code at /Users/craigy/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 6s (mobile) • 9FEC4074-90F2-4DBB-9841-50CE77CDC18A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!`

output from adding that one line for barcodetypes results in this output 


`Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ../.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:
    388:19: warning: coercion of implicitly unwrappable value of type 'InAppWebView_IBWrapper?' to 'Any' does not unwrap optional
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
   ../.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:
    26:19: note: implicitly unwrapped property 'containerWebView' declared here
        @IBOutlet var containerWebView: InAppWebView_IBWrapper!
                      ^
   ../.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:
    388:19: note: provide a default value to avoid this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                       ?? <#default value#>
   ../.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:
    388:19: note: force-unwrap the value to avoid this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                      !
   ../.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:
    388:19: note: explicitly cast to 'Any' with 'as Any' to silence this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                       as Any
   ../.pub-cache/git/qr_code_scanner-5b3f228cad622d0d650e262672c3ad4ba86ac6a1/ios/Classes/QRView.swift:101:44:
    warning: no calls to throwing functions occur within 'try' expression
                    allowedBarcodeTypes.append(try QRCodeTypes[arg]!)
                                               ^
   ../.pub-cache/git/qr_code_scanner-5b3f228cad622d0d650e262672c3ad4ba86ac6a1/ios/Classes/QRViewFactory.swift:20:13:
    warning: variable 'dictionary' was never mutated; consider changing to 'let' constant
            var dictionary =  args as! Dictionary<String, Double>
            ~~~ ^
            let
    lib/UI/ScanPage.dart:213:54: Error: A value of type 'BarcodeFormat' can't be assigned to a variable of type 'BarcodeTypes'.
     - 'BarcodeFormat' is from 'package:barcode_scan/gen/protos/protos.pbenum.dart'
     ('../../../../.pub-cache/hosted/pub.dartlang.org/barcode_scan-3.0.1/lib/gen/protos/protos.pbenum.dart').
     - 'BarcodeTypes' is from 'package:qr_code_scanner/src/types/barcode.dart'
     ('../../../../.pub-cache/git/qr_code_scanner-5b3f228cad622d0d650e262672c3ad4ba86ac6a1/lib/src/types/barcode.dart').
        controller.setAllowedBarcodeTypes([BarcodeFormat.dataMatrix]);
                                                         ^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 6s.`

**Comment by LeLunZ** [comment]
Okay. 
`flutter clean` and then rebuilding also didn’t work?

But these logs seem suspicious. 

> lib/UI/ScanPage.dart:213:54: Error: A value of type 'BarcodeFormat' can't be assigned to a variable of type 'BarcodeTypes'.
> - 'BarcodeFormat' is from 'package:barcode_scan/gen/protos/protos.pbenum.dart'
('../../../../.pub-cache/hosted/pub.dartlang.org/barcode_scan-3.0.1/lib/gen/protos/protos.pbenum.dart').
> - 'BarcodeTypes' is from 'package:qr_code_scanner/src/types/barcode.dart'
('../../../../.pub-cache/git/qr_code_scanner-5b3f228cad622d0d650e262672c3ad4ba86ac6a1/lib/src/types/barcode.dart').
controller.setAllowedBarcodeTypes([BarcodeFormat.dataMatrix]);

You have a mismatch of BarcodeTypes and BarcodeFormat. 
Could it be that some other packages also define these? 

Try to import BarcodeFormat with a prefix like this:
https://stackoverflow.com/questions/57951672/try-using-as-prefix-for-one-of-the-imported-directives-or-hiding-the-name-from

**Comment by craigbrown-nist** [comment]
> Try to import BarcodeFormat with a prefix like this:
> https://stackoverflow.com/questions/57951672/try-using-as-prefix-for-one-of-the-imported-directives-or-hiding-the-name-from

Right you are!  controller.setAllowedBarcodeTypes([**BarcodeTypes**.dataMatrix]); works when specified as from qr-code.

Very much appreciate your help!
C

**Comment by bharathiselvan** [comment]
@LeLunZ 
Thanks for the great PR...
First time when i scan PDF 417 barcode, it takes about 20 to 30 seconds to scan. And in the scanned data stream, i am receiving the data multiple times... It seems to scan the data multiple times and sending it..

Are you facing this issue?..

**Comment by LeLunZ** [comment]
> @LeLunZ
> Thanks for the great PR...
> First time when i scan PDF 417 barcode, it takes about 20 to 30 seconds to scan. And in the scanned data stream, i am receiving the data multiple times... It seems to scan the data multiple times and sending it..
> 
> Are you facing this issue?..

Na, doesn’t have the issue with 20 seconds delay. Which iOS android version? 

When you point the camera on to the QR code and don’t withdraw it instantly it Scans it multiple times. 

In your on_qr_code_scanned (in the stream handler) you could do something like this: 

```dart
bool handling_qr_code = false;

void on_qr_code_scanned(qr_code){
    if(handling_qr_code)
        return;
    handling_qr_code = true;
    // handle your QR code. Show User a new view etc. when finishing do this: 
    handling_qr_code = false;
}
```
Hope that the code formatting doesn’t suck. Doing it on my smartphone.

**Comment by bharathiselvan** [comment]
okay.. I will do this, test and update you..

**Comment by bharathiselvan** [comment]
I modified the code as you have mentioned above, but still the same behaviour...
In Android, its happening very frequently and in iOS its happening some times ( 1 out of 5 times)...
Android Version - 9 and iOS version - 13.6.1

**Comment by bharathiselvan** [comment]
I m attaching the logs here
[barcode_scan_logs.zip](https://github.com/juliuscanute/qr_code_scanner/files/5430474/barcode_scan_logs.zip)

**Comment by LeLunZ** [comment]
> I modified the code as you have mentioned above, but still the same behaviour...
> In Android, its happening very frequently and in iOS its happening some times ( 1 out of 5 times)...
> Android Version - 9 and iOS version - 13.6.1

Could you also share a small code example where I can reproduce the error ;) would help a lot! 

What are you programmatically doing after getting the qr_code? Opening a new view?

**Comment by bharathiselvan** [comment]
I just modified the example program and running.. Attaching the compressed code (zipped) here.. I am trying to scan the driving license...
[barcode_scanner.dart.zip](https://github.com/juliuscanute/qr_code_scanner/files/5432417/barcode_scanner.dart.zip)

If this widget is called from main directly, after every scan the app has to be restarted.. 

Below are the logs from my debug console.. I have removed the captured data from here.. See if its helpful..

D/CameraPreview( 7681): pause()
V/SensorManager( 7681): unRegisterListener by android.view.OrientationEventListener$SensorEventListenerImpl
D/CameraInstance( 7681): Closing camera
E/Parcel  ( 7681): Reading a NULL string not supported here.
I/Choreographer( 7681): Skipped 1 frames!  The application may be doing too much work on its main thread.
D/CameraInstance( 7681): Camera is closed, not requesting preview
Restarted application in 2,045ms.
W/PlatformViewsController( 7681): Creating a virtual display of size: [720, 1512] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [720, 1456].
D/CameraPreview( 7681): resume()
D/CameraInstance( 7681): Opening camera
V/SensorManager( 7681): RegisterListener bmi160 Accelerometer Non-wakeup type:1 delay:200000us by android.view.OrientationEventListener$SensorEventListenerImpl
E/Parcel  ( 7681): Reading a NULL string not supported here.
E/libc    ( 7681): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    ( 7681): Access denied finding property "vendor.camera.aux.packagelist"
E/Camera  ( 7681): facelock mHypnusCtrl is ture in cameraInitVersion
E/Camera  ( 7681): mHypnusCtrl is true
E/libc    ( 7681): Access denied finding property "vendor.camera.hal1.packagelist"
E/CheckPermission( 7681): camera-code= 3
D/WindowManager( 7681): Add to mViews: DecorView@4e9fef6[MainActivity], this = android.view.WindowManagerGlobal@1b68099,pkg=com.sg.SGUniverse
D/CameraPreview( 7681): resume()
W/CameraPreview( 7681): initCamera called twice
V/SensorManager( 7681): unRegisterListener by android.view.OrientationEventListener$SensorEventListenerImpl
E/Parcel  ( 7681): Reading a NULL string not supported here.
V/SensorManager( 7681): RegisterListener bmi160 Accelerometer Non-wakeup type:1 delay:200000us by android.view.OrientationEventListener$SensorEventListenerImpl
E/Parcel  ( 7681): Reading a NULL string not supported here.
I/Choreographer( 7681): Skipped 1 frames!  The application may be doing too much work on its main thread.
E/libc    ( 7681): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    ( 7681): Access denied finding property "vendor.camera.aux.packagelist"
D/CameraInstance( 7681): Configuring camera
I/CameraManager( 7681): Camera Display Orientation: 90
I/CameraManager( 7681): Initial camera parameters: preview-size=1920x1080;video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=1920x1440,1920x1080,1600x1200,1600x720,1440x1080,1280x960,1280x768,1280x720,1200x1200,1024x768,800x600,864x480,800x480,720x480,640x640,640x480,480x640,480x320,352x288,320x240,240x320,176x144,160x120;video-size-values=4000x1800,3840x2160,3264x1472,2592x1944,2688x1512,2304x1728,2048x1536,1920x1440,1920x1080,2560x800,1600x1200,1600x720,1440x1080,1280x960,1280x768,1280x720,1200x1200,1024x768,800x600,864x480,800x480,720x480,640x640,640x480,480x640,480x320,352x288,320x240,240x320,176x144,160x120;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=7000,30000;preview-fps-range-values=(15000,15000),(20000,20000),(7000,24000),(24000,24000),(7000,30000),(30000,30000);preview-frame-rate-values=15,20,24,30;picture-size=4000x3000;picture-size-values=4000x3000,4000x1800,3840x2160,3264x2448,3264x1472,3200x2400,3000x3000,2592x1944,2688x1512,2448x2448,2304x1728,2048x1536,1920x1440,1920x1080,2560x800,1600x1200,1600x720,1440x1080,1280x960,1280x768,1280x720,1200x1200,1024x768,800x600,864x480,800x480,720x480,640x640,640x480,480x640,480x320,352x288,320x240,240x320,176x144,160x120;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua;antibanding=auto;antibanding-values=off,60hz,50hz,auto;scene-mode=auto;scene-mode-values=auto,landscape,snow,beach,sunset,night,portrait,sports,steadyphoto,candlelight,fireworks,party,night-portrait,theatre,action,hdr;flash-mode=off;flash-mode-values=off,auto,on,torch,red-eye;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.05;horizontal-view-angle=64.5939;vertical-view-angle=50.7288;exposure-compensation=0;max-exposure-compensation=12;min-exposure-compensation=-12;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,109,118,127,136,145,154,163,172,181,190,200,209,218,227,236,245,254,263,272,281,290,299,309,318,327,336,345,354,363,372,381,390,399,409,418,427,436,445,454,463,472,481,490,499,509,518,527,536,545,554,563,572,581,590,599,609,618,627,636,645,654,663,672,681,690,699,709,718,727,736,745,754,763,772,781,790,799,809,818,827,836,845,854,863,872,881,890,899,909,918,927,936,945,954,963,972,981,990,999;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-stabilization=false;video-stabilization-supported=true;video-snapshot-supported=false
I/CameraConfiguration( 7681): Requesting focus mode value from among: [auto]
I/CameraConfiguration( 7681): Supported focus mode values: [infinity, auto, macro, continuous-video, continuous-picture]
I/CameraConfiguration( 7681): Can set focus mode to: auto
I/CameraConfiguration( 7681): Focus mode already set to auto
I/CameraConfiguration( 7681): Requesting flash mode value from among: [off]
I/CameraConfiguration( 7681): Supported flash mode values: [off, auto, on, torch, red-eye]
I/CameraConfiguration( 7681): Can set flash mode to: off
I/CameraConfiguration( 7681): Flash mode already set to off
I/PreviewScalingStrategy( 7681): Viewfinder size: 1512x720
I/PreviewScalingStrategy( 7681): Preview in order of preference: [1600x720, 1280x720, 1920x1080, 1280x768, 1440x1080, 1600x1200, 1280x960, 1920x1440, 864x480, 1024x768, 800x480, 1200x1200, 720x480, 800x600, 640x480, 480x320, 640x640, 320x240, 352x288, 480x640, 160x120, 176x144, 240x320]
I/CameraManager( 7681): Final camera parameters: video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=1920x1440,1920x1080,1600x1200,1600x720,1440x1080,1280x960,1280x768,1280x720,1200x1200,1024x768,800x600,864x480,800x480,720x480,640x640,640x480,480x640,480x320,352x288,320x240,240x320,176x144,160x120;video-size-values=4000x1800,3840x2160,3264x1472,2592x1944,2688x1512,2304x1728,2048x1536,1920x1440,1920x1080,2560x800,1600x1200,1600x720,1440x1080,1280x960,1280x768,1280x720,1200x1200,1024x768,800x600,864x480,800x480,720x480,640x640,640x480,480x640,480x320,352x288,320x240,240x320,176x144,160x120;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=7000,30000;preview-fps-range-values=(15000,15000),(20000,20000),(7000,24000),(24000,24000),(7000,30000),(30000,30000);preview-frame-rate-values=15,20,24,30;picture-size=4000x3000;picture-size-values=4000x3000,4000x1800,3840x2160,3264x2448,3264x1472,3200x2400,3000x3000,2592x1944,2688x1512,2448x2448,2304x1728,2048x1536,1920x1440,1920x1080,2560x800,1600x1200,1600x720,1440x1080,1280x960,1280x768,1280x720,1200x1200,1024x768,800x600,864x480,800x480,720x480,640x640,640x480,480x640,480x320,352x288,320x240,240x320,176x144,160x120;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua;antibanding=auto;antibanding-values=off,60hz,50hz,auto;scene-mode=auto;scene-mode-values=auto,landscape,snow,beach,sunset,night,portrait,sports,steadyphoto,candlelight,fireworks,party,night-portrait,theatre,action,hdr;flash-mode=off;flash-mode-values=off,auto,on,torch,red-eye;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.05;horizontal-view-angle=64.5939;vertical-view-angle=50.7288;exposure-compensation=0;max-exposure-compensation=12;min-exposure-compensation=-12;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,109,118,127,136,145,154,163,172,181,190,200,209,218,227,236,245,254,263,272,281,290,299,309,318,327,336,345,354,363,372,381,390,399,409,418,427,436,445,454,463,472,481,490,499,509,518,527,536,545,554,563,572,581,590,599,609,618,627,636,645,654,663,672,681,690,699,709,718,727,736,745,754,763,772,781,790,799,809,818,827,836,845,854,863,872,881,890,899,909,918,927,936,945,954,963,972,981,990,999;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-stabilization=false;video-stabilization-supported=true;video-snapshot-supported=false;preview-size=1600x720
I/CenterCropStrategy( 7681): Preview: 720x1600; Scaled: 720x1600; Want: 720x1512
I/CameraPreview( 7681): Starting preview
D/CameraInstance( 7681): Starting preview
I/AutoFocusManager( 7681): Current focus mode 'auto'; use auto focus? true
W/System  ( 7681): A resource failed to call release.
D/DecoderThread( 7681): Found barcode in 9 ms
D/DecoderThread( 7681): Found barcode in 11 ms
D/DecoderThread( 7681): Found barcode in 10 ms
D/DecoderThread( 7681): Found barcode in 11 ms
D/DecoderThread( 7681): Found barcode in 10 ms
D/DecoderThread( 7681): Found barcode in 10 ms
D/DecoderThread( 7681): Found barcode in 14 ms
D/DecoderThread( 7681): Found barcode in 9 ms
D/DecoderThread( 7681): Found barcode in 16 ms
I/m.sg.SGUnivers( 7681): Waiting for a blocking GC ProfileSaver
I/m.sg.SGUnivers( 7681): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 12.284ms
D/DecoderThread( 7681): Found barcode in 53 ms
D/DecoderThread( 7681): Found barcode in 49 ms
---- Data is captured here --------- (I have removed it)
Application finished.
Exited (sigterm)

**Comment by LeLunZ** [comment]
> I just modified the example program and running.. Attaching the compressed code (zipped) here.. I am trying to scan the driving license...
> [barcode_scanner.dart.zip](https://github.com/juliuscanute/qr_code_scanner/files/5432417/barcode_scanner.dart.zip)
> 
> If this widget is called from main directly, after every scan the app has to be restarted..
> 


I tested your code and found some issues. 
You always need to restart the app, because you implemented it wrong.

it should be like this:

```dart
if (_handled_qr_code) {
        return;
      }
_handled_qr_code = true;
// do your stuff
_handled_qr_code = false;
```

you did this:
```dart
if (_handled_qr_code) {
        return;
      }
// do your stuff
_handled_qr_code = true;
```
so the bool never will be false...

I implemented a small example to show you, how it should be done:

```dart
import 'package:flutter/material.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

void main() => runApp(MaterialApp(home: QRViewExample()));

const flashOn = 'FLASH ON';
const flashOff = 'FLASH OFF';
const frontCamera = 'FRONT CAMERA';
const backCamera = 'BACK CAMERA';

class QRViewExample extends StatefulWidget {
  const QRViewExample({
    Key key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _QRViewExampleState();
}

class _QRViewExampleState extends State<QRViewExample> {
  QRViewController controller;
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');

  bool _handled_qr_code = false;

  @override
  void initState(){
    super.initState();
    QRView.requestCameraPermission();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          Expanded(
            flex: 4,
            child: QRView(
              key: qrKey,
              onQRViewCreated: _onQRViewCreated,
            ),
          ),
        ],
      ),
    );
  }

  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    this.controller.setAllowedBarcodeTypes([BarcodeTypes.pdf417]);

    controller.scannedDataStream.listen((String scanData) {
      if (_handled_qr_code) {
        return;
      }
      _handled_qr_code = true;
      showDialog(
        context: context,
        builder: (BuildContext context){
          return AlertDialog(
            title: Text('Continue with scanning!'),
            actions: [FlatButton(
                child: Text('Yes'),
                onPressed: (){
                  // Continue with scanning
                  _handled_qr_code = false;
                  Navigator.of(context).pop();
                }
            ),FlatButton(
                child: Text('Do nothing'),
                onPressed: (){
                }
            ),],
          );
        },
      );
    });
  }

  @override
  void dispose() {
    this.controller.dispose();
    super.dispose();
  }
}
```

I hope that this will help you.

**Comment by bharathiselvan** [comment]
Thanks for tour response ..In my actual program, i will call this widget from another widget, so every time this widget will get created and _handled_qr_code will get reset..
I found the issue... As i don't have a US driving issue, my friend who is in US, shared the driving license as a image with not so good quality and poor lighting .. Hence, It takes time to decode that image....

**Comment by juliansteenbakker** [comment]
First of all thank you for this PR. You added some new features and this needs some time to review and test. The first priority right now is to fix bugs, so i will move this PR to a further release.

**Comment by LeLunZ** [comment]
> First of all thank you for this PR. You added some new features and this needs some time to review and test. The first priority right now is to fix bugs, so i will move this PR to a further release.

Yeah thx, for answering ;) 
If you need help with something just tell me what todo, and I will see if it is within my capabilities.

**Comment by juliansteenbakker** [comment]
@LeLunZ can you merge the upstream changes and fix the mergeconflicts? After that i can check everything and merge it.

**Comment by LeLunZ** [comment]
> @LeLunZ can you merge the upstream changes and fix the mergeconflicts? After that i can check everything and merge it.

No problem, I will do this in the next few days.

**Comment by juliansteenbakker** [comment]
I have cherrypicked your code and added the upstream changes to it in a new branch so you don't have to merge this anymore. I'm fixing a few more bugs and after that i will release this. Thank you for your contribution!

**Comment by LeLunZ** [comment]
> I have cherrypicked your code and added the upstream changes to it in a new branch so you don't have to merge this anymore. I'm fixing a few more bugs and after that i will release this. Thank you for your contribution!

Ahh okay. In which branch did you add the features?

**Comment by juliansteenbakker** [comment]
[You can find it here.](https://github.com/juliuscanute/qr_code_scanner/tree/86-select-camera-on-start) I still need to fix the permission alert dialog and test the selected types function.

**Pull request closed without merging**
