### PR TITLE
fix: platform break changes

### PR DESCRIPTION
**Pull request by xeinebiu**
Fix for the issue https://github.com/juliuscanute/qr_code_scanner/issues/511

### CODE REVIEW

**Comment by SwiftyFlow** [comment]
this still didn't help. cannot run on android simulator... about to remove this dependency but to replace with what?

**Comment by xeinebiu** [comment]
@SwiftyFlow  please post some logs. What exactly did not run ?

**Comment by juliansteenbakker** [comment]
This issue is currently only existent on the MASTER channel of Flutter so i still need to test if this change doesn't break the STABLE channel.

**Comment by xeinebiu** [comment]
> This issue is currently only existent on the MASTER channel of Flutter so i still need to test if this change doesn't break the STABLE channel.

Most probably the stable version won't be compatible with this change. 

Maybe an alpha version should be released, or we simply wait for the next stable version of Flutter, test it and then maybe merge?

**Comment by srmanc** [comment]
Can confirm that this works on master tip. The problem right now is that flutter introduced:
1) breaking changes in native Android code
2) bad obfuscation code in stable and beta branch.
Fix for both is in master, so you can see how this complicates things.

I would very much appreciate an alpha version.

**Comment by aaassseee** [comment]
Hi @juliansteenbakker, any idea when will this pull request getting merged?

**Review by kinhvodoi92 — APPROVED** [review]

**Comment by juliansteenbakker** [comment]
Sorry for the slow response, but LGTM !

**Pull request merged**
