### PR TITLE
Fix getting camera permissions

### PR DESCRIPTION
**Pull request by via-guy**
`onPermissionSet` was never called for iOS

### CODE REVIEW

**Comment by kuamanet** [comment]
Will this be released any time soon?

**Comment by alexeynobody** [comment]
This PR is very much needed for merge and release ASAP. Thanks.

**Comment by FantaMagier** [comment]
This PR could handle my problem, Good Job! I opend this issue, maybe it is only the missing permission : https://github.com/juliuscanute/qr_code_scanner/issues/319

**Comment by surister** [comment]
@juliansteenbakker

**Comment by juliansteenbakker** [comment]
Sorry for the delay, thanks for your contribution!

**Pull request merged**
