### PR TITLE
add invert scan feature for android

### LINKED ISSUE #403: [BUG] White QRCode with other Background Color cannot be scanned.
**Describe the bug**
White QRCode with other Background Color cannot be scanned.

**Flutter information**
[✓] Flutter (Channel master, 2.5.0-7.0.pre.185, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.185 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2526cb07cb (11 hours ago), 2021-08-21 23:42:01 -0400
    • Engine revision 4783663ee4
    • Dart version 2.15.0 (build 2.15.0-41.0.dev)

**Device (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android11
PS: iPhone/iOS will not have this issue.

**Screenshots**
Left part of below image CANNOT be scanned with qr_code_scanner v0.5.2. 
In my case, white QRCode with blue background  cannot be scanned also.
Right part is ok.

**Additional context**
...

### PR DESCRIPTION
**Pull request by akkalbhor**
This PR fixes #403 
@juliuscanute Please review and merge ASAP

### CODE REVIEW

**Comment by juliansteenbakker** [comment]
You need to add an empty function for flutter_qr_web like so:
```
  @override
  Future<void> scanInvert() {
    // TODO: implement scanInvert
    throw UnimplementedError();
  }
```

**Comment by akkalbhor** [comment]
I have added the function in flutter_qr_web

**Comment by akkalbhor** [comment]
@juliansteenbakker can you merge this PR and update the library as well?

**Comment by akkalbhor** [comment]
@juliansteenbakker can you please update the library on pub.dev?

**Comment by JT501** [comment]
please upload a new version to pub.dev, we need this fix. 🙏🏻

**Pull request merged**
