### PR TITLE
Added web support

### LINKED ISSUE #124: [FEATURE] [PLATFORM] Web support
Any update or working for web support?

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
Fixes #124

I added coarse web support. In particular, this is support for QR codes, preview and some controller options. As both Flutter's web support for platform views and JavaScript's video processing capabilities are something in between nonexistent and unusable, support is definitely not perfect.

Anyway, it is something like usable.

### CODE REVIEW

**Comment by TheOneWithTheBraid** [comment]
@juliuscanute Are you still active on the repository? Web support would be great!

**Comment by juliansteenbakker** [comment]
@TheOneWithTheBraid sorry for the delay. This looks cool! can you please format the files accordingly with `flutter format`.

**Comment by TheOneWithTheBraid** [comment]
@juliansteenbakker I just did.

**Comment by juliansteenbakker** [comment]
Thank you for the fast response. There are still some analyzer issues. Also after looking through the code i think its best to not merge this in the master branch but instead to create a new beta-web branch and release this as a beta. What do you think about this?

The analyzer issues that needs to be fixed:
```
   info • The value of the field '_mediaRecorder' isn't used • lib/src/web/flutter_qr_web.dart:59:23 • unused_field
   info • The value of the field '_canvasKey' isn't used • lib/src/web/flutter_qr_web.dart:76:9 • unused_field
   info • Private field could be final • lib/src/web/flutter_qr_web.dart:78:10 • prefer_final_fields
   info • The value of the field '_scaleFactor' isn't used • lib/src/web/flutter_qr_web.dart:78:10 • unused_field
   info • The declaration '_captureImage' isn't referenced • lib/src/web/flutter_qr_web.dart:204:19 • unused_element
   info • Only use double quotes for strings containing single quotes • lib/src/web/jsqr.dart:6:5 • prefer_single_quotes
   info • Only use double quotes for strings containing single quotes • lib/src/web/media.dart:4:5 • prefer_single_quotes
   info • Only use double quotes for strings containing single quotes • lib/src/web/media.dart:9:5 • prefer_single_quotes
 ```

**Comment by TheOneWithTheBraid** [comment]
I see the point. The implementation is not perfect yet - not at last due to flutter's awful platform view support on web and javasctipt's awful image processing capabilities. I will fix the issues caught by the linter later today.

**Comment by TheOneWithTheBraid** [comment]
I now fixed the analysis issues. Anyway, maybe in future I will completely re-implement the web code. But still I think as of now it's better to have coarse support for web than no support.

**Comment by TheOneWithTheBraid** [comment]
Could you please publish to pub.dev?

**Comment by juliansteenbakker** [comment]
Yes i will later this day. I'm first gonna check if there is anything else i could update or fix

**Pull request merged**
