### PR TITLE
Changed minSdkVersion to 19

### PR DESCRIPTION
**Pull request by JFreakDK**
This should fix https://github.com/juliuscanute/qr_code_scanner/issues/90
I changed the minSdk version to 19 but only tested that version on the emulator. I had a device running sdk 23 and the example app worked on that device.

### CODE REVIEW

**Comment by dspicher** [comment]
Tested with the example app.
Thanks for the PR @JFreakDK!

**Comment by TMSantos** [comment]
hey @dspicher how can I test with mindSDk 19? latest version still asks for 24 which is too much for my requirements, thanks a lot

**Comment by dspicher** [comment]
@TMSantos until the next version is published you can specify `qr_code_scanner` as a Git dependency:
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by TMSantos** [comment]
oh Right! thanks a lot, just started on Flutter and I missed this

**Comment by anhvu-sg** [comment]
hi @dspicher , just a question
When will you release the new version 0.0.14?

**Comment by DhavalRKansara** [comment]
@juliuscanute When will you release 0.0.14 with min SDK version 19 in android?

**Comment by TMSantos** [comment]
All you need to do to get min SDK 19 without release is:
`  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git`

**Comment by DhavalRKansara** [comment]
> All you need to do to get min SDK 19 without release is:
> qr_code_scanner:
> git:
> url: https://github.com/juliuscanute/qr_code_scanner.git

yeah thanks @TMSantos

**Pull request merged**
