### PR TITLE
Fix an issue when Scanner size is broken after iPad rotation

### LINKED ISSUE #34: iOS wrong dimension after orientation change
I used the example of the plugin for testing purposes.

https://github.com/juliuscanute/qr_code_scanner/blob/master/example/lib/main.dart

I have modified the main.dart file as follows:

```
...
children: <Widget>[
          Expanded(
            child: Center(
              child: SizedBox(
                width: 300.0,
                height: 200.0,
                child: QRView(
                  key: qrKey,
                  onQRViewCreated: _onQRViewCreated,
                ),
              ),
            ),
            flex: 4,
          ),
          Expanded(
...
```

After that I noticed that the camera preview is centered as desired with a width of 300.0 and a height of 200.0 when starting the app. If I rotate the device (iPad mini) from portrait to landscape or vice versa the camera preview becomes twice as big and overflows the SizedBox.

If in the file qr_code_scanner.dart on line 56 the width fix is set to 300.0 and the height fix is set to 200.0 everything works as desired!

### PR DESCRIPTION
**Pull request by alexshikov**
The issue happens because MTBBarcodeScanner automatically handles rotation.
See https://github.com/mikebuss/MTBBarcodeScanner/blob/aecff1571f41dd69b6898b850c9a978da85a5054/Classes/ios/Scanners/MTBBarcodeScanner.m\#L465

The fix is to detect Flutter QrView size change and adjust scanner's layout frame on iOS

Potentially fixes #34, #87 and #112

### CODE REVIEW

**Comment by alexshikov** [comment]
The usage of `QrView` should be wrapped with `SizeChanged` notification (see updated example). I wasn't sure if we should move this code into plugin code because in that case the `QrView` widget should hold `QRViewController` reference.

**Comment by alexshikov** [comment]
Are there any steps required to accept this PR?

**Comment by RenanDelfanti** [comment]
I have this issue on android, this pull request fix on android too?

**Comment by alexshikov** [comment]
@RenanDelfanti all the changes in this PR are iOS oriented, so it should NOT influence Android behaviour.

To be honest, we didn't notice this issues on Android devices (either tablets or phones)

**Comment by RenanDelfanti** [comment]
@alexshikov When I turn the android screen orientation I see a black screen, needing to restart the app.
I will test on different devices to see if this problem continues

**Comment by RenanDelfanti** [comment]
@alexshikov I fixed my problem with your sample code, pausing and resuming the controller when changing the screen size / orientation

**Comment by itsbalamurali** [comment]
@juliuscanute any update on merging this one?

**Comment by njustin** [comment]
Same issue here, with an iPad, going from portrait to landscape breaks the layout. The view expand outside of the Container.

**Comment by juliansteenbakker** [comment]
@alexshikov can you please merge the changes from master into this PR?

**Comment by juliansteenbakker** [comment]
Merged in #177

**Pull request closed without merging**
