### PR TITLE
[iOS] Fix disposing camera from memory

### LINKED ISSUE #113: iOS (Android not tested): PlatformQrView does not get disposed after closing widget
On iOS 14, the green dot which indicates the app is accessing phone's camera is still ON even I has closed the widget.

### PR DESCRIPTION
**Pull request by Rag3h**
Fixes #113 memory leak which caused not disposing camera from memory.

### CODE REVIEW

**Comment by dspicher** [comment]
Thanks a lot for the PR! I have asked the people on #113 to test this, will merge as soon as I get a confirmation.

**Review by sjoerd0301 — APPROVED** [review]

**Comment by Falynsky** [comment]
@dspicher What about this fix? :)

**Comment by dspicher** [comment]
Merged. Feel free to use
```
qr_code_scanner:
    git:
      url: git://github.com/juliuscanute/qr_code_scanner.git
```
if you want to use this before the next release.

**Comment by Falynsky** [comment]
@dspicher Amazing, thanks! Do we know when the next release will be avaiable? :)

**Comment by LeLunZ** [comment]
> @dspicher Amazing, thanks! Do we know when the next release will be avaiable? :)

@juliuscanute isn't that active....could take a long time xD
I would just use the git url for now.

**Pull request merged**
